### PR TITLE
sipsess: fix 100rel_answer_not_allowed

### LINKED ISSUE #176: PRACK/100rel tests unstable
The PRACK/100rel tests introduced in https://github.com/baresip/retest/pull/167 (by me) sometimes cause the CI pipelines to fail (e.g. see https://github.com/baresip/re/pull/658).

This is most likely a timing issue and needs to be investigated.

### PR DESCRIPTION
**Pull request by maximilianfridrich**
Refactor test to first unsuccesfully try to send answer, then send answer on PRACK received and close everything cleanly on established.

Fixes #176.

### CODE REVIEW

**Comment by maximilianfridrich** [comment]
The task "Install packages linux" failed. Could someone trigger a re-check?

File: src/sipsess.c [hunk 1]
```diff
@@ -935,6 +935,8 @@ int test_sipsess_100rel_answer_not_allowed(void)
 	test.rel100_a = REL100_ENABLED;
 	test.rel100_b = REL100_ENABLED;
 	test.conn_action = CONN_PROGR_ANS;
+	test.answ_ret_code = 22;
```
Comment (cspiel1) [inline src/sipsess.c:938]: I would prefer "EINVAL".

Comment (maximilianfridrich) [reply src/sipsess.c:938]: Done in #180.
